/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.49
 * Generated at: 2025-11-19 09:50:38 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html lang=\"en\">\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"UTF-8\">\n");
      out.write("  <title>Welcome Dots Animation</title>\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Montserrat:700&display=swap\" rel=\"stylesheet\">\n");
      out.write("  <style>\n");
      out.write("    .welcome-animation {\n");
      out.write("      position: relative;\n");
      out.write("      width: 350px;\n");
      out.write("      height: 100px;\n");
      out.write("      margin: 60px auto;\n");
      out.write("      display: flex;\n");
      out.write("      align-items: center;\n");
      out.write("      justify-content: center;\n");
      out.write("      background: #f8f8fa;\n");
      out.write("      border-radius: 16px;\n");
      out.write("      box-shadow: 0 8px 28px rgba(33, 150, 243, 0.07);\n");
      out.write("    }\n");
      out.write("    .dot {\n");
      out.write("      position: absolute;\n");
      out.write("      width: 14px;\n");
      out.write("      height: 14px;\n");
      out.write("      border-radius: 50%;\n");
      out.write("      background: #3498db;\n");
      out.write("      opacity: 0.8;\n");
      out.write("      animation: bounce-dot 1.5s cubic-bezier(.73,.02,.31,.84) infinite;\n");
      out.write("      animation-delay: calc(var(--i) * 0.2s);\n");
      out.write("    }\n");
      out.write("    .dot:nth-child(1) { left: 30px; top: 60px; }\n");
      out.write("    .dot:nth-child(2) { left: 90px; top: 30px; }\n");
      out.write("    .dot:nth-child(3) { left: 150px; top: 80px; }\n");
      out.write("    .dot:nth-child(4) { left: 210px; top: 40px; }\n");
      out.write("    .dot:nth-child(5) { left: 270px; top: 60px; }\n");
      out.write("    .dot:nth-child(6) { left: 330px; top: 30px; }\n");
      out.write("    .dot:nth-child(7) { left: 70px; top: 80px; }\n");
      out.write("\n");
      out.write("    @keyframes bounce-dot {\n");
      out.write("      0%,100% { transform: translateY(0);}\n");
      out.write("      20% { transform: translateY(-40px);}\n");
      out.write("      35% { transform: translateY(0);}\n");
      out.write("      60% { opacity: 0;}\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    .welcome-text {\n");
      out.write("      position: absolute;\n");
      out.write("      left: 50%;\n");
      out.write("      top: 50%;\n");
      out.write("      transform: translate(-50%,-50%);\n");
      out.write("      font-family: 'Montserrat', Arial, sans-serif;\n");
      out.write("      font-size: 3em;\n");
      out.write("      color: #3498db;\n");
      out.write("      letter-spacing: 0.15em;\n");
      out.write("      opacity: 0;\n");
      out.write("      animation: revealText 2s 1.6s forwards;\n");
      out.write("    }\n");
      out.write("    @keyframes revealText {\n");
      out.write("      from { opacity: 0; }\n");
      out.write("      to { opacity: 1; }\n");
      out.write("    }\n");
      out.write("  </style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <div class=\"welcome-animation\">\n");
      out.write("    <span class=\"dot\" style=\"--i:0\"></span>\n");
      out.write("    <span class=\"dot\" style=\"--i:1\"></span>\n");
      out.write("    <span class=\"dot\" style=\"--i:2\"></span>\n");
      out.write("    <span class=\"dot\" style=\"--i:3\"></span>\n");
      out.write("    <span class=\"dot\" style=\"--i:4\"></span>\n");
      out.write("    <span class=\"dot\" style=\"--i:5\"></span>\n");
      out.write("    <span class=\"dot\" style=\"--i:6\"></span>\n");
      out.write("    <span class=\"welcome-text\">WELCOME</span>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
